--- 
:ask_for_cc: false
:discard_snippets_from_encrypted_messages: false
:accounts: 
  :default: 
    :signature: /home/dan/.signature
    :sendmail: /usr/bin/msmtp -oem -ti
    :email: dangra@gmail.com
    :alternates: 
    - daniel@insophia.com
    :name: "Daniel Gra\xC3\xB1a"
:ask_for_bcc: false
:editor: /usr/bin/vim
:default_attachment_save_dir: ""
:thread_by_subject: false
:ask_for_subject: true
:poll_interval: 300
:edit_signature: false
:confirm_no_attachments: true
:wrap_width: 0
:ask_for_from: false
:confirm_top_posting: true
:slip_rows: 0
:ask_for_to: true
:sent_source: maildir:/home/dan/mail/insophia
:jump_to_open_message: true
