# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

[username]
disabled = true

[hostname]
ssh_only = false
detect_env_vars = [ '!TMUX', 'SSH_CONNECTION' ]

[vcsh]
format = '[🆅 $repo](bold blue) '
