return {
  "nvim-treesitter/nvim-treesitter",
  opts = {
    ensure_installed = {
      "c",
      "bash",
      "eex",
      "elixir",
      "go",
      "gomod",
      "gosum",
      "gowork",
      "caddy",
      "cmake",
      "css",
      "devicetree",
      "gitcommit",
      "gitignore",
      "glsl",
      "go",
      "graphql",
      "http",
      "html",
      "javascript",
      "just",
      "kconfig",
      "rust",
      "scss",
      "sql",
    },
  },
}
